# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on: push
name: deploy  
jobs:
  deploy:
  name: deploy
  runs-on: ubuntu-latest
  steps:
  -run: echo "Estamos ejecutando nuestro wprkflow"
